# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e76f5c84ec002083d6654530bde8104af52fbd97bf33650160b904002cc9b9d9c3cb650a07d7446a202a2677551288ff5618907791b4b39d2e55015c129c16

test:
  secret_key_base: 9a0007aa5e98b4b285a35d3c682cd6a7681ea99151c12d2175a4bb9986dd30d07ae652cc33ca98bbc13a7e1b730476cbe088cd206a98ac9caf1690fafe2023ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
